### ISSUE TITLE
Reinforced Double Chests Can Be On Two Groups With /ctf

### ISSUE THREAD

**Issue by Crushtoe** [Civcraft/Citadel#177] opened 2016-03-22 17:58 UTC
Placing down one chest with /ctf on group A will put it on group A. Then switch to /ctf B, and place a chest next to it. The double chest will now be on two different groups, and can be opened by someone on only one of the groups.

It might be possible to use this to access a chest you shouldn't be able to, such as someone's drop chest, by putting down a fortified chest right next to it and opening that side.

**Comment by ProgrammerDan** [comment] 2016-03-22 17:59
That's an issue. Wonder what change broke that protection ...

**Comment by Crushtoe** [comment] 2016-03-22 18:01
Noticed it 3 days ago while putting down chests in my home in Gimmel.

**Comment by Maxopoly** [comment] 2016-03-22 18:02
Just tested this and cant reproduce it, it was actively preventing placing a chest next to it. Did you do anything else?

**Comment by Crushtoe** [comment] 2016-03-22 18:03
I had put down the first chest and reinforced it with /ctr, and later made it a double chest. I had used /ctf when I made it a double chest, but it may of just been a fluke.

**Comment by ProgrammerDan** [comment] 2016-03-22 18:04
Just looked through the code, and i'll be closing this.

If you have CHEST on both groups this will be allowed. Some foreign group where you don't have access won't be able to place a chest next to yours and steal from you.

Having multiple groups accessible against the same chest is working as designed. The only rule that is tested is if the person placing the new fortified chest has access to the connected chest already or not.

**Closed by ProgrammerDan** 2016-03-22 18:04 UTC
Labels: bug, P0 - ASAP
