### ISSUE TITLE
Reinforced new doors can be opened by anyone

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/Citadel#97] opened 2015-05-11 06:46 UTC
The reinforcing itself seems to work now, but even after deleting the group the new doors could still be opened.

**Comment by WildWeazel** [comment] 2015-05-11 14:28
Were you or someone in the group standing nearby? Due to MC limitations we can only check proximity to group members, not who triggered the signal.

What command(s) did you use on the door?

**Comment by rourke750** [comment] 2015-05-11 23:40
Action is confirmed.  Gah I hate deprecated stuff.  None of these new doors are under the same system as the regular door.

**Comment by ttk2** [comment] 2015-05-12 02:03
did they deprecate what we used to use for doors?

**Comment by rourke750** [comment] 2015-05-12 02:03
No they just haven't included the new ones in it

**Comment by rourke750** [comment] 2015-05-13 14:20
I really hope this can be fixed in spigot because it would be simple in citadel but it isnt the right way.

**Comment by ttk2** [comment] 2015-05-24 01:33
this is resolved.

**Closed by ttk2** 2015-05-24 01:33 UTC
Labels: bug, Civtest - Pending verification, P1 - Critical
